import React from 'react';

// about section

export default () => (
  <section id='help'>
    <h3>
      <i className='fas fa-question-circle heading_icon'></i>About this tool
    </h3>
    <p>
      This tool uses a machine learning model trained on 1.7 million{' '}
      <a href='https://www.ncbi.nlm.nih.gov/pmc/'>PubMed Central</a> documents
      to recommend suitable journals based on the textual content of your{' '}
      <a href='https://www.biorxiv.org/'>bioRxiv</a> preprint. This tool
      provides a "map" of all documents within{' '}
      <a href='https://www.ncbi.nlm.nih.gov/pmc/tools/openftlist/'>
        {' '}
        PubMed Central's Open Access Corpus{' '}
      </a>
      , and plots where your <a href='https://www.biorxiv.org/'>bioRxiv</a>{' '}
      preprint falls on this map. Each square bin on the map represents a group
      of papers that share similar textual content. Click on a square to view
      more information about papers contained in a given bin.
    </p>
    <p>
      This tool also contains a set of 50 <i> principal components</i> (PCs)
      that were generated by performing Principal Component Analysis (PCA) on
      the <a href='https://www.biorxiv.org/'>bioRxiv</a> corpus. Each PC
      represents two high level concepts characterized by keywords of various
      strengths. These keywords are illustrated within the word cloud thumbnails
      above the map. Select a thumbnail to color the map by that specific PC.
      Deeper orange cells will be papers that correlate more with the orange
      keywords in the image, and vice versa for blue. For information on how
      this tool works, see the{' '}
      <a href='https://github.com/greenelab/annorxiver-journal-recommender#annorxiver-journal-recommender'>
        readme on GitHub
      </a>
      .
    </p>
  </section>
);
